FORM BUILD_CATEGORY_100  CHANGING PT_ALV_FIELDCAT TYPE LVC_T_FCAT.


  DATA: L_TEXT(30),
        L_COL_POS TYPE I.


  DATA : LT_FCAT TYPE SLIS_T_FIELDCAT_ALV,
         LS_FCAT TYPE LVC_S_FCAT.

  DATA : LT_FCAT_TMP TYPE LVC_T_FCAT,
         LV_FDNAME   TYPE FIELDNAME.

  CALL FUNCTION 'REUSE_ALV_FIELDCATALOG_MERGE'
    EXPORTING
      I_PROGRAM_NAME         = SY-REPID
      I_INTERNAL_TABNAME     = GV_INTTAB100
      I_INCLNAME             = SY-REPID
    CHANGING
      CT_FIELDCAT            = LT_FCAT
    EXCEPTIONS
      INCONSISTENT_INTERFACE = 1
      PROGRAM_ERROR          = 2
      OTHERS                 = 3.
  IF SY-SUBRC <> 0.
  ENDIF.

  DATA : LV_TABNM         LIKE FELD-NAME.
  FIELD-SYMBOLS: <FS_TAB> TYPE STANDARD TABLE.
  CONCATENATE GV_INTTAB100 '[]' INTO LV_TABNM.
  ASSIGN (LV_TABNM) TO <FS_TAB>.

  CALL FUNCTION 'LVC_TRANSFER_FROM_SLIS'
    EXPORTING
      IT_FIELDCAT_ALV = LT_FCAT
    IMPORTING
      ET_FIELDCAT_LVC = PT_ALV_FIELDCAT
    TABLES
      IT_DATA         = <FS_TAB>.

  DATA : PS_FCAT_MENGE TYPE LVC_S_FCAT,
         PS_FCAT_DMBTR TYPE LVC_S_FCAT,
         PS_FCAT_DMAVG TYPE LVC_S_FCAT,
         LV_COLPOS     TYPE LVC_COLPOS.

* )Qty/Amt)참조 필드 READ
  CLEAR: PS_FCAT_MENGE, PS_FCAT_DMBTR.
  READ TABLE PT_ALV_FIELDCAT INTO PS_FCAT_MENGE
                             WITH KEY FIELDNAME = 'MENGE'.
  IF SY-SUBRC EQ 0.
    PS_FCAT_MENGE-NO_ZERO = C_X.
    LV_COLPOS = PS_FCAT_MENGE-COL_POS.
    CLEAR : PS_FCAT_MENGE-QFIELDNAME.
  ENDIF.
  READ TABLE PT_ALV_FIELDCAT INTO PS_FCAT_DMBTR
                             WITH KEY FIELDNAME = 'DMBTR'.
  IF SY-SUBRC EQ 0.
    PS_FCAT_DMBTR-NO_ZERO = C_X.
    CLEAR : PS_FCAT_MENGE-CFIELDNAME.
  ENDIF.
  READ TABLE PT_ALV_FIELDCAT INTO PS_FCAT_DMAVG
                             WITH KEY FIELDNAME = 'DMAVG'.
  IF SY-SUBRC EQ 0.
    PS_FCAT_DMAVG-NO_ZERO = C_X.
    CLEAR : PS_FCAT_MENGE-CFIELDNAME.
  ENDIF.

* Beginning Inventory(QTY/AMT)
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_MENGE TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_MENGE-FIELDNAME '_BI' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F01.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C700'.
  LS_FCAT-NO_OUT = C_X.               " 숨김처리 / 24.08.20
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_DMBTR TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_DMBTR-FIELDNAME '_BI' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F02.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C700'.
  LS_FCAT-NO_OUT = C_X.               " 숨김처리 / 24.08.20
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_DMAVG TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_DMAVG-FIELDNAME '_BI' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F81.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C700'.
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.


* Group code
  IF GT_ZMMT0010[] IS INITIAL.
    PERFORM GET_GROUP_ZMMT0010.
  ENDIF.

  LOOP AT GT_ZMMT0010 INTO DATA(LS_ZMMT0010).

    ADD 1 TO LV_COLPOS.
    CLEAR : LS_FCAT.
    MOVE-CORRESPONDING PS_FCAT_MENGE TO LS_FCAT.
    LS_FCAT-COL_POS = LV_COLPOS.
    CONCATENATE PS_FCAT_MENGE-FIELDNAME '_' LS_ZMMT0010-ZGROUP
           INTO LS_FCAT-FIELDNAME.
    CONCATENATE LS_ZMMT0010-ZTEXT TEXT-F91 INTO  LS_FCAT-REPTEXT.
    LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT.
    IF LS_FCAT-FIELDNAME+6(2) = 'GR'.
      LS_FCAT-EMPHASIZE = 'C500'.
    ELSE.
      LS_FCAT-EMPHASIZE = 'C510'.
    ENDIF.
    LS_FCAT-QFIELDNAME = 'MENIS'.
    APPEND LS_FCAT TO PT_ALV_FIELDCAT.

    ADD 1 TO LV_COLPOS.
    CLEAR : LS_FCAT.
    MOVE-CORRESPONDING PS_FCAT_DMBTR TO LS_FCAT.
    LS_FCAT-COL_POS = LV_COLPOS.
    CONCATENATE PS_FCAT_DMBTR-FIELDNAME '_' LS_ZMMT0010-ZGROUP
           INTO LS_FCAT-FIELDNAME.
    CONCATENATE LS_ZMMT0010-ZTEXT TEXT-F92 INTO  LS_FCAT-REPTEXT.
    LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT.
    IF LS_FCAT-FIELDNAME+6(2) = 'GR'.
      LS_FCAT-EMPHASIZE = 'C500'.
    ELSE.
      LS_FCAT-EMPHASIZE = 'C510'.
    ENDIF.
    LS_FCAT-QFIELDNAME = 'WAERS'.
    APPEND LS_FCAT TO PT_ALV_FIELDCAT.

    ADD 1 TO LV_COLPOS.
    CLEAR : LS_FCAT.
    MOVE-CORRESPONDING PS_FCAT_DMAVG TO LS_FCAT.
    LS_FCAT-COL_POS = LV_COLPOS.
    CONCATENATE PS_FCAT_DMAVG-FIELDNAME '_' LS_ZMMT0010-ZGROUP
           INTO LS_FCAT-FIELDNAME.
    CONCATENATE LS_ZMMT0010-ZTEXT TEXT-F93 INTO  LS_FCAT-REPTEXT.
    LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT.
    IF LS_FCAT-FIELDNAME+6(2) = 'GR'.
      LS_FCAT-EMPHASIZE = 'C500'.
    ELSE.
      LS_FCAT-EMPHASIZE = 'C510'.
    ENDIF.
    APPEND LS_FCAT TO PT_ALV_FIELDCAT.

  ENDLOOP.

* Stock In Transit(QTY/AMT)
  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_MENGE TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_MENGE-FIELDNAME '_SIT' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F07.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C710'.
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_DMBTR TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_DMBTR-FIELDNAME '_SIT' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F08.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C710'.
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_DMAVG TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_DMAVG-FIELDNAME '_SIT' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F84.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C710'.
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

* Ending Inventory(QTY/AMT)
  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_MENGE TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_MENGE-FIELDNAME '_EI' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F03.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C300'.
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_DMBTR TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_DMBTR-FIELDNAME '_EI' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F04.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C300'.
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_DMAVG TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_DMAVG-FIELDNAME '_EI' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F82.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C300'.
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

* Ending Inventory_SG(QTY/AMT)
  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_MENGE TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_MENGE-FIELDNAME '_SG_EI' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F05.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C300'.
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_DMBTR TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_DMBTR-FIELDNAME '_SG_EI' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F06.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C300'.
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

  ADD 1 TO LV_COLPOS.
  CLEAR : LS_FCAT.
  MOVE-CORRESPONDING PS_FCAT_DMAVG TO LS_FCAT.
  LS_FCAT-COL_POS = LV_COLPOS.
  CONCATENATE PS_FCAT_DMAVG-FIELDNAME '_SG_EI' INTO LS_FCAT-FIELDNAME.
  LS_FCAT-SCRTEXT_L = LS_FCAT-REPTEXT = TEXT-F83.
  LS_FCAT-SCRTEXT_S = LS_FCAT-SCRTEXT_M = LS_FCAT-SCRTEXT_L.
  LS_FCAT-EMPHASIZE = 'C300'.
  APPEND LS_FCAT TO PT_ALV_FIELDCAT.

* 참조 필드 삭제
  DELETE PT_ALV_FIELDCAT WHERE FIELDNAME EQ 'MENGE'
                            OR FIELDNAME EQ 'DMBTR'
                            OR FIELDNAME EQ 'DMAVG' .
  SORT PT_ALV_FIELDCAT BY COL_POS.

  LOOP AT PT_ALV_FIELDCAT ASSIGNING <FS_ALV_FIELDCAT>.
    CLEAR <FS_ALV_FIELDCAT>-KEY.

    CASE <FS_ALV_FIELDCAT>-FIELDNAME.
      WHEN 'BUKRS'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'MATNR'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'MAKTX'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'MAT_DESC'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F53.
      WHEN 'MAKTX2'. "Material Description2 MAKT-MAKTX+0(18)
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F54.
      WHEN 'MAGRV'. "Packing Material
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F55.
      WHEN 'SPART'. "Division
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F56.
      WHEN 'SPART_TX'. "Division Desc.
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F57.
      WHEN 'WERKS'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'LIFNR'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'LIFNR_TX'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
        <FS_ALV_FIELDCAT>-COLTEXT = TEXT-F58.
      WHEN 'LGORT'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'CHARG'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
* batch key Start - screen 0400
      WHEN 'SQR'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
        <FS_ALV_FIELDCAT>-REPTEXT = TEXT-F52.
      WHEN 'SOBKZ'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'PARTNER'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
      WHEN 'NAME_ORG1'.
        <FS_ALV_FIELDCAT>-KEY = C_X.
        <FS_ALV_FIELDCAT>-REPTEXT = TEXT-F51.
* batch key end

      WHEN 'MEINS'.
*        <fs_alv_fieldcat>-col_pos = 996.
      WHEN 'WAERS'.
*        <fs_alv_fieldcat>-col_pos = 997.
      WHEN 'INFO'.
        <FS_ALV_FIELDCAT>-COL_POS = 998.
      WHEN 'MARK'.
        <FS_ALV_FIELDCAT>-COL_POS = 999.

      WHEN 'XXXX'.
        <FS_ALV_FIELDCAT>-NO_OUT = C_X.
    ENDCASE.

  ENDLOOP.

  SORT PT_ALV_FIELDCAT BY COL_POS.


ENDFORM.                    " BUILD_CATEGORY_100
